### ISSUE TITLE
Feature: permissions nodes

### ISSUE THREAD

**Issue by SlimeDog** [moltendorf/IntelliDoors#2]
I would like to use IntelliDoors as a donor perk. That would require permissions nodes to control access to the features. The minimum could be just a few nodes to enable/disable iron components (with defaults indicated):

`- intellidoors.doors.iron-door.single.interact.enabled: false`
`- intellidoors.doors.iron-door.pair.interact.enabled: false`
`- intellidoors.doors.iron-trapdoor.single.interact.enabled: false`
`- intellidoors.doors.iron-trapdoor.pair.interact.enabled: false`

although the complete list would be more expansive:

`- intellidoors.enabled: true`
`- intellidoors.single.interact.reset.enabled: true`
`- intellidoors.single.redstone.reset.enabled: true`
`- intellidoors.pair.interact.sync: true`
`- intellidoors.pair.interact.reset.enabled: true`
`- intellidoors.pair.redstone.sync: true`
`- intellidoors.pair.redstone.reset.enabled: true`
`- intellidoors.doors.wooden-door.single.interact.enabled: true`
`- intellidoors.doors.wooden-door.single.interact.reset.enabled: true`
`- intellidoors.doors.wooden-door.single.redstone.enabled: true`
`- intellidoors.doors.wooden-door.single.redstone.reset.enabled: true`
`- intellidoors.doors.wooden-door.pair.interact.enabled: true`
`- intellidoors.doors.wooden-door.pair.interact.sync: true`
`- intellidoors.doors.wooden-door.pair.interact.reset.enabled: true`
`- intellidoors.doors.wooden-door.pair.redstone.enabled: true`
`- intellidoors.doors.wooden-door.pair.redstone.sync: true`
`- intellidoors.doors.wooden-door.pair.redstone.reset.enabled: true`
`- intellidoors.doors.iron-door.single.interact.enabled: false`
`- intellidoors.doors.iron-door.single.interact.reset.enabled: true`
`- intellidoors.doors.iron-door.single.redstone.enabled: true`
`- intellidoors.doors.iron-door.single.redstone.reset.enabled: true`
`- intellidoors.doors.iron-door.pair.interact.enabled: false`
`- intellidoors.doors.iron-door.pair.interact.sync: true`
`- intellidoors.doors.iron-door.pair.interact.reset.enabled: true`
`- intellidoors.doors.iron-door.pair.redstone.enabled: true`
`- intellidoors.doors.iron-door.pair.redstone.sync: true`
`- intellidoors.doors.iron-door.pair.redstone.reset.enabled: true`

etc.

**Comment by moltendorf** [comment]
I've set aside some time to work on this today, hopefully I'll have it done tonight.

**Comment by maezred** [comment]
So the simplest ones would be whether or not a player can interact with the door; other features (e.g. redstone sync, etc.) would be better suited for my preferences system.

While I will use the same names as the config names used for controlling the doors (allowing the server owner ultimate flexibility), only a few names will actually be used. I'll list which ones they are in the config and in the readme.

**Comment by SlimeDog** [comment]
Closed due to dev abandonment.
